use_frameworks!

platform :ios, '10.0'

target 'LYNetworkService_Example' do
  pod 'LYNetworkService', :path => '../'

  target 'LYNetworkService_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
  target 'Extension' do
     inherit! :search_paths
     pod 'Alamofire'
     pod 'SwiftyJSON'
     pod 'HandyJSON'
   end
end
